Repository shardeum/shardeum-validator-gui, pull requests merged in 2025-04, with the labels that each got.

#105 SHARD-2126: Change onboarding text to use generic network name
  pages/onboarding/index.tsx
Labels: Review effort 1/5

#108 Add RPC_SERVER_URL env
  pages/_app.tsx
Labels: Review effort 1/5

#107 SHARD-2146: refactor onboarding so components can be excluded based on chain
  components/onboarding/ClaimTokensStep.tsx
  components/onboarding/StakeStep.tsx
  components/onboarding/StartNodeStep.tsx
  components/onboarding/WalletConnectStep.tsx
  hooks/useTokenClaimPhase.ts
  pages/onboarding/index.tsx
Labels: Review effort 4/5

#110 SHARD-1842: better error messaging around Stake Lock
  components/molecules/StakeDisplay.tsx
  model/node-status.ts
Labels: Review effort 2/5

#112 SHARD-2210: handle case of connecting different wallet
  components/molecules/StakeDisplay.tsx
Labels: Review effort 2/5

#113 SHARD-2210: handle case of connecting different wallet
  components/molecules/StakeDisplay.tsx
Labels: Review effort 2/5
